language: node_js
node_js:
    - '6'
dist: trusty
install: |
        ./.travis/install.sh
script: |
      ./.travis/script.sh
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
cache: false
sudo: required
